### ISSUE TITLE
Phar for version 4.2.0

### ISSUE THREAD

**Issue by OndraM** [Roave/BackwardCompatibilityCheck#169]
Hi, it seems phar file is missing from assets of release 4.2.0:
https://github.com/Roave/BackwardCompatibilityCheck/releases

Could you please add it?

Thanks!

**Comment by asgrim** [comment]
@Ocramius hmm, this was the automated release, is there something missing there?

**Comment by Ocramius** [comment]
Seems like the credentials aren't correct:
https://travis-ci.org/Roave/BackwardCompatibilityCheck/jobs/609657677

**Comment by sebastianbergmann** [comment]
What is the status of this? Thanks!

**Comment by Ocramius** [comment]
Inspecting the docs, I think this needs to be changed:

https://github.com/Roave/BackwardCompatibilityCheck/blob/026a96b4f523544b93f5d1228d83cd5303d7f976/.travis.yml#L29-L30

Specifically, the docs (https://docs.travis-ci.com/user/deployment/releases/) say that the format is:

```yml
deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    tags: true
```

So we have a `secure:` too much there.
