### ISSUE TITLE
Compare with last tag on the same branch as the target branch

### ISSUE THREAD

**Issue by greg0ire** [Roave/BackwardCompatibilityCheck#268]
```gherkin
Given `doctrine/migrations` has tags 3.0.0, 3.0.1 and 2.3.0
 When I open a PR against 2.3.x (for instance)
 Then the tool should detect that the last minor version is 2.3.0
```

Right now [it detects that the last version is… 3.0.0](https://github.com/doctrine/migrations/pull/1069/checks?check_run_id=1335686748#step:5:173), which is confusing.

I believe this could be done by detected what branch the commit being tested is based on. On most CI systems, the commit being tested is the result of a merge between the target branch and the last commit on PR. This means that the detection can be performed easily by looking at the parent commits, provided they are fetched, which implies doing stuff like this (example with Github Actions):

```

      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 2
```
